//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringService")]
public interface IStringService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/CountOccurrences", ReplyAction="http://tempuri.org/IStringService/CountOccurrencesResponse")]
    int CountOccurrences(string firstString, string secondString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/CountOccurrences", ReplyAction="http://tempuri.org/IStringService/CountOccurrencesResponse")]
    System.Threading.Tasks.Task<int> CountOccurrencesAsync(string firstString, string secondString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringServiceChannel : IStringService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringServiceClient : System.ServiceModel.ClientBase<IStringService>, IStringService
{
    
    public StringServiceClient()
    {
    }
    
    public StringServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int CountOccurrences(string firstString, string secondString)
    {
        return base.Channel.CountOccurrences(firstString, secondString);
    }
    
    public System.Threading.Tasks.Task<int> CountOccurrencesAsync(string firstString, string secondString)
    {
        return base.Channel.CountOccurrencesAsync(firstString, secondString);
    }
}
